SAP_PM_AI/DowntimeReasonSuggetstionWeb/urls.py
from django.contrib import admin
from django.urls import include, path
from django.urls import include, path
from django.conf.urls import url
from django.conf import settings


# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns = [
#         path('__debug__/', include(debug_toolbar.urls)),
#         path('', include(('downtimeML.urls', 'downtimeML'), namespace='downtimeML')),
#         path('admin/', admin.site.urls),
#         url(r'^downtimeML/', include(('downtimeML.urls', 'downtimeML'), namespace='downtimeML')),

#     ] 

urlpatterns = [
    path('', include(('downtimeML.urls', 'downtimeML'), namespace='downtimeML')),
    path('admin/', admin.site.urls),
    url(r'^downtimeML/', include(('downtimeML.urls', 'downtimeML'), namespace='downtimeML')),
     ] 


SAP_PM_AI/downtimeML/urls.py
from django.urls import path
from django.conf.urls import url

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    url(r'^(?P<num1>\d+)/(?P<num2>\d+)/$', views.tensorflowtest, name='tensorflowtest'),

    # path('ajax/load_categories/', views.load_categories, name='ajax_load_categories'),
    path('getDowntimeReason/', views.getDowntimeReason, name='getDowntimeReason'),
]

SAP_PM_AI/downtimeML/models.py
from django.db import models

class BusinessUnit(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name

class Line(models.Model):
    businessunit = models.ForeignKey(BusinessUnit, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name

class Category(models.Model):
    name = models.CharField(max_length=30)
    ename = models.CharField(max_length=30)

    def __str__(self):
        return self.name

class Station(models.Model):
    line = models.ForeignKey(Line, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    number = models.CharField(max_length=30)
    name = models.CharField(max_length=50)
    ename = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class MachineGroup(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name

class MachineType(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name      

class Issue(models.Model):

    TYPES = (
        ('ISSUE', '문제'),
        ('SOLUTION', '조치'),
    )

    type = models.CharField(max_length=30, choices=TYPES)
    businessunit = models.ForeignKey(BusinessUnit, on_delete=models.CASCADE)
    machinegroup = models.ForeignKey(MachineGroup, on_delete=models.CASCADE)
    machinetype = models.ForeignKey(MachineType, on_delete=models.CASCADE)
    content = models.CharField(max_length=100)
    econtent = models.CharField(max_length=100,blank=True)

    def __str__(self):
        return self.content

SAP_PM_AI/downtimeML/views.py

import os, pickle
import numpy as np
from django.http import HttpResponse
from django.shortcuts import render
from django.utils.safestring import mark_safe

from .models import Category
from modelCreation import Continental

def loadCategories():
    categories = Category.objects.all().order_by('name')

    # template로 보낼 때 공백 문자열 값이 사라지는 문제 해결
    for c in categories:
        c.ename = c.ename.replace(' ','_')

    return categories

def index(request):
    return render(request, 'downtimeML/Index.html', {'categories': loadCategories()})

import tensorflow as tf
logs_path = '/home/dc/pyweb'

# open pk file
with open(os.path.dirname(__file__) + '\cont_instance.pkl' , 'rb') as f:
    print("file is : " + f.name)
    cont = pickle.load(f)

# model 생성하기
model = cont.build_model(use_equip_info=True)

# 미리 학습해둔 모델의 파라미터 불러오기
model.load_weights(os.path.dirname(__file__) + '\model_top-100.hdf5' )

global graph
graph = tf.get_default_graph() 

def getDowntimeReason(request):

    sentence = request.GET.get('contexttext')
    equip_info = request.GET.get('catetoryselect')
    equip_info = equip_info.replace('_',' ') # replace 했던 ' '를 다시 복원

    # 새로운 관측치 전처리 (model input 형태에 맞게)
    sentence, equip_info = cont.make_new_test_data(sentence, equip_info)

    with graph.as_default():
        y_pred = model.predict([sentence, equip_info])[0]
    #y_pred = model._make_predict_function([sentence, equip_info])

    # Get top-5 predictions (labels & probabilities)
    k = 10 # 추천 수
    top_k_indices = np.argsort(y_pred)[::-1][:k]  # Descending order
    top_k_labels = cont.label2idx.inverse_transform(top_k_indices)  # integer label -> original string
    top_k_proba = y_pred[top_k_indices]  # probabilities

    suggestions = []
    for i, l, p in zip(top_k_indices, top_k_labels, top_k_proba):
        s = dict(line = i , name = l , accuracy = round(p*100,2))
        suggestions.append(s)

    return render(request, 'downtimeML/Index.html', {'suggestions':suggestions,'categories': loadCategories()})

def tensorflowtest(request, num1, num2):
    n1 = int(num1)
    n2 = int(num2)

    x =  tf.placeholder(tf.int32)
    y =  tf.placeholder(tf.int32)

    add = tf.add(x, y)
    with tf.Session() as sess:
        summary_writer = tf.summary.FileWriter(logs_path, graph=tf.get_default_graph())
        z = sess.run(add, feed_dict = {x:n1, y:n2})
    return HttpResponse("sum of %s and %s is %s" %(num1, num2, z))

SAP_PM_AI/DowntimeReasonSuggetstionWeb/templates/layout.html
{% load static %}
<!doctype html>
<html>

<head>
    <meta charset="utf-8" />
    <title>AI SYSTEM</title>
    <link rel="stylesheet" href="{% static "bootstrap/dist/css/bootstrap.min.css" %}" />
    <!-- <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootswatch/3.3.7/flatly/bootstrap.min.css" /> -->
    {% block extra_head %}{% endblock %}
</head>

<body>
    <nav style="background-color:orange"  class="navbar navbar-inverse">
    <!-- <nav style="background-color:orange" class="navbar navbar-default"> -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <div style="font-size: xx-large; color:black">
                    <a class=" navbar-brand" href="{% url "downtimeML:index" %}">AI SYSTEM</a>
            </div>

        </div>
        <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="active"><a href="{% url "downtimeML:index" %}">DOWNTIME REASONS</a></li>
            </ul>
        </div>
        <!--/.nav-collapse -->
        </div>
    </nav>

    <script src="{% static "jquery/dist/jquery.min.js" %}"></script>
    <script src="{% static "bootstrap/dist/js/bootstrap.min.js" %}"></script>
    <script src="{% static "jquery.csrf.js" %}"></script>

    {% block content %}
    {% endblock %}

    <hr>

    <div class="container">
        <footer>
            <p>2019 &copy; <a href="http://icmesasv.cw01.contiwan.com:8778/iGate/wip" target=_blank">MES igate</a>
            </p>
        </footer>
    </div>

    {% block extra_body %}
    {% endblock %}
</body>

</html>

SAP_PM_AI/downtimeML/templates/downtimeML/Index.html
{% extends "downtimeML/layout.html" %}

{% load bootstrap4 %}

{% block content %}

<div class="container">
  <div class="row">
    <div class="col-sm-12">

      <br/>

      <form method="GET" action="{% url 'downtimeML:getDowntimeReason' %}" >

          <!-- {% csrf_token %} -->
          <div class="form-group">
            <label for="select1">장비를 선택하세요</label>

            <select class="form-control" id="catetoryselect" name="catetoryselect">
                {% for category in categories %}
                  <option value={{ category.ename }}>{{ category.name }}</option>
                {% empty %}
                  <option selected>Please register Categories</option>
                {% endfor %}
            </select>
          </div>

          <div class="form-group">
            <label for="text1">키워드를 입력하세요!</label>
            <textarea class="form-control" id="contexttext" name="contexttext" rows="1"></textarea>
          </div>

          <button type="submit" class="btn btn-primary btn-block">SUGGEST TO ME!</button>
        </form>

      <br/>

      <h2>SUGGESTION LIST</h2>
      <table border="1" class="table">
        <thead>
          <tr>
            <th>ID</th>
            <th>SUGGESTION</th>
            <th>ACCURACY(%)</th>
          </tr>
        </thead>
        <tbody>
            {% for item in suggestions %}
            <tr>
              <td>{{ item.line }}</td>
              <td>{{ item.name }}</td>
              <td>{{ item.accuracy }}</td>
            </tr>
            {% empty %}
            <tr>
              <td colspan="4">No Suggestion from AI </td>
            </tr>
            {% endfor %}
        </tbody>
      </table>
      
    </div>
  </div>
</div>


{% endblock %}

SAP_PM_AI/downtimeML/templates/downtimeML/layout.html
{% extends "layout.html" %}